apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-svc
  labels:
    {{- include "omni-nodeselector-mutator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "omni-nodeselector-mutator.selectorLabels" . | nindent 4 }}
